name: Pull Requests

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  test:
    name: Cargo Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
