name: Cargo Test

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        os: ["macos-latest", "windows-latest"]
    runs-on: '${{ matrix.os }}'
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cargo test --all
